FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Chatovací aplikace
Api pro jednoduchou chatovací aplikaci

Tomáš Erlebach

## Api [/api]

### Test připojení  [GET]
+ Request (application/json)
        {
            test: "test"
        } 
+ Response 200 (application/json)

        {
            test: "test"
        }
 
## Uživatelé [/api/getAllUsers]

### List všech uživatelů [GET]

+ Response 200 (application/json)

        {
            [
              {
                _id: "61cf4309c5e731812a1e8703",
                login: "marek",
                name: "Marek Starý",
                profilePicture: "images/marek.png"
               },
                {
                _id: "61cf43e5c5e731812a1e8704",
                login: "jan",
                name: "Jan Malý",
                profilePicture: "images/avatar.png"
               }
            ]
        }
+ Response 500 (application/json)
    {error: "err"}
        

## Konverzace [/api//conversation?username={username}&participant={participant}]

### Načíst konverzaci [GET]

+ Parameters
    + username (String) přihlášený uživatel
    + participant (String) účastník konverzace

+ Response 200 (application/json)
{
    conversation: {
                _id: "61d2be0bf0bfa870708691c6",
                participants: ["jan", "marek"]
                }
        messages: {
            [
                {
                message: "Ahoj, jak je? ",
                type:"text",
                conversation:"61d2be0bf0bfa870708691c6",
                sender:"marek"
                }
            ]
      }
 }
+ Response 500 (application/json)
    {error: "err"}
    
    
## Kontakty [/api/getUserContactList?username={username}]

### Načíst už kontakty uživatele [GET]

+ Parameters
    + username (String) přihlášený uživatel

+ Response 200 (application/json)
[
    {
        "_id": "61cf43e5c5e731812a1e8704",
        "login": "jan",
        "name": "Jan Malý",
        "profilePicture": "images/avatar.png",
        "status": "Offline"
    },
    {
        "_id": "61d21f087d61cd1521b4a9d7",
        "login": "ondra",
        "name": "Ondra Velký",
        "profilePicture": "images/avatar.png",
        "status": "Offline"
    }
]
 